# @package _global_

defaults:
  - _self_
  - data: tn3k.yaml
  - model: beitSeg.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

ckpt_path: USFM_20231222.pth
