# @package _global_

defaults:
  - _self_
  - data: mnist.yaml
  - model: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

ckpt_path: ???
