defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.log_dir}/${task_name}/${tag}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns_${tag}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
